[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen.workspace = true
paste = "1.0.15"
eyre.workspace = true

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
