name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: "Install other"
        run: |
          rustup default nightly
          rustup component add rustfmt clippy
      - uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: "latest"
      # - name: cargo fmt & clippy
      #   run: |
      #     cargo fmt --all -- --check
      #     cargo clippy -- --deny=warnings
      # - name: Install just
      #   run: |
      #     cargo install just
      # - name: Verify justfile
      #   run: |
      #     just --list
      # - name: Test math crate
      #   run: |
      #     just test-math

      - name: build
        run: |
          cd app && trunk build --release

      # Conditional deployment
      - name: Deploy preview for preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: preview-${{ github.event.pull_request.number }}
          folder: app/dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to main
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: app/dist
          token: ${{ secrets.GITHUB_TOKEN }}
