name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: rust-src
      - uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: "latest"
      - name: Install just
        run: |
          cargo install just
      - name: Verify justfile
        run: |
          just --list
      - name: Test crate
        run: |
          just test
